// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMv8jvr8z6yOe7GHL0rNRYeFAi7WUjEHo',
    appId: '1:198033400155:web:9f25e40cfe506a06087a7e',
    messagingSenderId: '198033400155',
    projectId: 'baseflutter-78ec5',
    authDomain: 'baseflutter-78ec5.firebaseapp.com',
    storageBucket: 'baseflutter-78ec5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNBSJRUXZC2zJdNFKeW0d09YrCtkZUQS4',
    appId: '1:198033400155:android:d45a5370f8ee85f9087a7e',
    messagingSenderId: '198033400155',
    projectId: 'baseflutter-78ec5',
    storageBucket: 'baseflutter-78ec5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4SmNEvdCXuaa95KnSCfXiILFHuhB2Fww',
    appId: '1:198033400155:ios:d4e00007f3b242dc087a7e',
    messagingSenderId: '198033400155',
    projectId: 'baseflutter-78ec5',
    storageBucket: 'baseflutter-78ec5.appspot.com',
    iosClientId: '198033400155-muo9vn39stbcsjqvjqk4r2h2dsua471m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4SmNEvdCXuaa95KnSCfXiILFHuhB2Fww',
    appId: '1:198033400155:ios:d4e00007f3b242dc087a7e',
    messagingSenderId: '198033400155',
    projectId: 'baseflutter-78ec5',
    storageBucket: 'baseflutter-78ec5.appspot.com',
    iosClientId: '198033400155-muo9vn39stbcsjqvjqk4r2h2dsua471m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationBase',
  );
}
